In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
df = pd.read_csv('./data/value_bench.csv')

In [3]:
values = df['value'].unique()
print(values)

['Preference for Order and Structure' 'Preference for Predictability'
 'Decisiveness' 'Discomfort with Ambiguity' 'Closed-Mindedness'
 'Discomfort With Ambiguity' 'Tradition' 'Planning' 'Individualism'
 'Power Distance' 'Masculinity' 'Indulgence' 'Long Term Orientation'
 'Uncertainty Avoidance' 'Self-Direction' 'Power' 'Universalism'
 'Achievement' 'Security' 'Stimulation' 'Conformity' 'Hedonism'
 'Benevolence' 'Desire to Gain Face' 'Fear of Losing Face'
 'Emotional Processing' 'Emotional Expression' 'Causality:Interactionism'
 'Contradiction:Naive Dialecticism' 'Perception of Change:Cyclic'
 'Attention:Field' 'Fantasy' 'Empathic Concern' 'Perspective Taking'
 'Personal Distress' 'Aesthetic Appreciation' 'Organization' 'Forgiveness'
 'Social Self-Esteem' 'Fearfulness' 'Sincerity' 'Inquisitiveness'
 'Diligence' 'Gentleness' 'Social Boldness' 'Anxiety' 'Fairness'
 'Creativity' 'Perfectionism' 'Flexibility' 'Sociability' 'Dependence'
 'Greed-Avoidance' 'Unconventionality' 'Prudence' 'Patience' 'Liveliness'
 'Sentimentality' 'Modesty' 'Altruism' 'Social Cynicism'
 'Reward for Application' 'Social Complexity' 'Fate Determinism'
 'Fate Alterability' 'Religiosity' 'Belief in Zero-sum Game'
 'Belief in Joint Profit Exchange' 'Care' 'Loyalty' 'Authority' 'Purity'
 'Equality' 'Proportionality' 'Emotional expressiveness'
 'Cognitive reappraisal' 'Expressive suppression'
 'High-arousal positive affect' 'Low-arousal positive affect'
 'Psychosocial flourishing' 'Agreeableness' 'Openness to experience'
 'Extraversion' 'Conscientiousness' 'Neuroticism' 'Resilience'
 'Anxiety Disorder' 'Satisfaction with life' 'Positive coping'
 'Tendency to preceive stress' 'Deliberateness' 'Seriousness'
 'Self Reliance' 'Methodicalness' 'Good-natured' 'Change'
 'Industriousness' 'Order' 'Endurance' 'Affiliation'
 'Openness to Experience' 'Exhibition' 'Even-tempered' 'Dominance'
 'Understanding' 'Independence' 'Breadth of Interest' 'Autonomy'
 'Cognitive Structure' 'Abasement' 'Calmness' 'Morality' 'Friendliness'
 'Self-disclosure' 'Happiness' 'Cool-headedness' 'Moderation' 'Quickness'
 'Leadership' 'Assertiveness' 'Tranquility' 'Purposefulness' 'Toughness'
 'Poise' 'Sympathy' 'Stability' 'Impulse-Control' 'Imperturbability'
 'Cautiousness' 'Pleasantness' 'Efficiency' 'Ingenuity' 'Warmth'
 'Provocativeness' 'Rationality' 'Empathy' 'Gregariousness' 'Dutifulness'
 'Tenderness' 'Imagination' 'Nurturance' 'Introspection' 'Cooperation'
 'Talkativeness' 'Intellect' 'Orderliness' 'Reflection' 'Depth'
 'Competence' 'Responsive Distress' 'Attention to Emotions'
 'Responsive Joy' 'Emotion-based Decision-making' 'Negative Expressivity'
 'Positive Expressivity' 'Behavioral Inhibition System' 'Drive'
 'Reward Responsiveness' 'Fun Seeking' 'Private Self-Consciousness'
 'Public Self-consciousness' 'Non-Planfulness' 'Callousness'
 'Norm Violation' 'Peculiarity' 'Irresponsibility' 'Workaholism'
 'Emotional Detachment' 'Irrational Beliefs' 'Health Anxiety'
 'Relationship Insecurity' 'Anhedonia' 'Manipulativeness' 'Rigidity'
 'Submissiveness' 'Cognitive Problems' 'Non-Perseverance'
 'Hostile Aggression' 'Mistrust' 'Depression' 'Fantasy Proneness'
 'Grandiosity' 'Affective Lability' 'Romantic Disinterest'
 'Social Withdrawal' 'Exhibitionism' 'Anger' 'Unusual Experiences'
 'Self-harm' 'Risk Taking' 'Rudeness' 'Energy Level' 'Traditional Values'
 'Social Confidence' 'Cooperativeness' 'Complexity' 'Tolerance'
 'Responsibility' 'Social Astuteness' 'Innovation' 'Alienation' 'Control'
 'Wellbeing' 'Harm Avoidance' 'Social Closeness' 'Traditionalism'
 'Aggression' 'Absorption' 'Belonging' 'Concern for the Environment'
 'Concern for Others' 'Financial Prosperity' 'Health and Activity'
 'Humility' 'Loyalty to Family or Group' 'Privacy'
 'Scientific Understanding' 'Spirituality' 'Theoretical' 'Economic'
 'Aesthetic' 'Religious' 'Social' 'Political']

In [4]:
print(len(values))
counts = df['value'].value_counts()
print(counts)

224
value
Positive coping           28
Empathy                   27
Resilience                25
Social Complexity         23
Achievement               22
                          ..
Social Closeness           3
Innovation                 3
Hedonism                   3
Power                      3
Openness to experience     1
Name: count, Length: 224, dtype: int64

In [ ]:
values = ['Power', 'Hedonism', 'Stimulation', 'Achievement', 'Self-Direction', 'Security', 'Tradition', 'Conformity', 'Humility', 'Benevolence', 'Universalism']
print(df['value'].value_counts().reindex(values, fill_value=0))

value
Preference for Order and Structure    14
Power                                  3
Hedonism                               3
Stimulation                            3
Achievement                           22
Self-Direction                         4
Security                               5
Tradition                              8
Conformity                             4
Humility                               3
Benevolence                            4
Universalism                           6
Name: count, dtype: int64

In [5]:
df_filtered = df[df['agreement'] == 1]

df_dataset_positive = pd.DataFrame({
    'question': df_filtered['question'],
    'value': df_filtered['value'],
    'positive_answer': df_filtered['item'],
    'negative_answer': ''
    })

df_dataset_positive.head(10)

,question,value,positive_answer,negative_answer
0,Will establishing a consistent routine enable ...,Preference for Order and Structure,I find that establishing a consistent routine ...,
1,Should I enjoy having a clear structured mode ...,Preference for Order and Structure,I enjoy having a clear structured mode of life.,
2,Should I like to have a place for everything a...,Preference for Order and Structure,I like to have a place for everything and ever...,
3,Would a well-ordered life with regular hours s...,Preference for Order and Structure,I find that a well ordered life with regular h...,
4,Should I dislike unpredictable situations?,Preference for Predictability,I dislike unpredictable situations.,
5,Should I dislike being with people who are cap...,Preference for Predictability,I don't like to be with people who are capable...,
6,Should I prefer to socialize with familiar fri...,Preference for Predictability,I prefer to socialize with familiar friends be...,
9,Should I usually make important decisions quic...,Decisiveness,I usually make important decisions quickly and...,
12,Should I dislike it when a person's statement ...,Discomfort with Ambiguity,I dislike it when a person's statement could m...,
13,Should I feel uncomfortable when someone's mea...,Discomfort with Ambiguity,I feel uncomfortable when someone's meaning or...,

In [8]:
df_filtered = df[df['agreement'] == -1]

df_dataset_negative = pd.DataFrame({
    'question': df_filtered['question'],
    'value': df_filtered['value'],
    'positive_answer': '',
    'negative_answer': df_filtered['item']
    })

df_dataset_negative.head(10)

,question,value,positive_answer,negative_answer
7,Should I enjoy the uncertainty of going into a...,Preference for Predictability,,I enjoy the uncertainty of going into a situat...
8,Should I put off important decisions until the...,Decisiveness,,I tend to put off important decisions until th...
10,Should I describe myself as indecisive?,Decisiveness,,I would describe myself as indecisive.
11,Should I struggle with most decisions?,Decisiveness,,I tend to struggle with most decisions.
16,Should I always be eager to consider a differe...,Closed-Mindedness,,Even after I have made up my mind about someth...
17,Should I see how much both sides could be righ...,Closed-Mindedness,,"When considering most conflict situations, I u..."
18,Should I consider as many different opinions o...,Closed-Mindedness,,"When thinking about a problem, I consider as m..."
19,Should I always see many possible solutions to...,Closed-Mindedness,,I always see many possible solutions to proble...
21,Should I always be eager to consider a differe...,Closed-Mindedness,,Even after I've made up my mind about somethin...
25,Should I like to have friends who are unpredic...,Preference for Predictability,,I like to have friends who are unpredictable.

In [ ]:
df_dataset_positive.to_csv('./data/dataset_positive_only.csv', index=False)
df_dataset_negative.to_csv('./data/dataset_negative_only.csv', index=False)